name: Docker Image Build & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "shreyasinghal29" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t <your-dockerhub-username>/fastapi-docker-cicd:latest .
          docker push <your-dockerhub-username>/fastapi-docker-cicd:latest
